adding info about clowder/generator repo to README.md
clowder-framework/pyclowder pull request #35
Opened 2021-07-22 14:21 UTC by Michael-D-Johnson

- Added a link to the clowder/generator repo
- mentioned that the onbuild is no longer maintained
- emphasized its recommended to use generator or building using your own base image and installing pyclowder

2022-02-15 22:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/clowder-framework/pyclowder?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/clowder-framework/pyclowder?pullRequest=35) before we can accept your contribution.<br/><hr/>**Michael Johnson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/clowder-framework/pyclowder?pullRequest=35) it.</sub>

2022-03-02 15:24 UTC, robkooper requested changes

2022-03-02 15:24 UTC, robkooper commented on README.md
> +To build wordcount as a Simple extractor docker image, users just simply assign two environment variables in Dockerfile shown below. EXTRACTION_FUNC is environment variable and has to be assigned as
```suggestion
To build wordcount as a an extractor docker image, users just simply assign two environment variables in Dockerfile shown below. EXTRACTION_FUNC is environment variable and has to be assigned as extraction function, where in wordcount.py, the extraction function is `wordcount`. Environment variable EXTRACTION_MODULE is the name of module file containing the definition of extraction function.
```

2022-03-02 15:24 UTC, robkooper commented on README.md
> +If you build the extractor as using the pyclowder:onbuild image, you will only need the following Dockerfile
```suggestion
**This is deprecated and the onbuild image is no longer maintained**
If you build the extractor as using the pyclowder:onbuild image, you will only need the following Dockerfile
```

2022-03-03 02:58 UTC, KastanDay commented
Love these documentation clarifications, thanks @Michael-D-Johnson!

2022-03-03 04:19 UTC, robkooper approved these changes

2022-03-03 04:20 UTC, merged